name: Generate Route Images

on:
  push:
    branches:
      - main
    paths:
      - 'routes/**.json'
      - 'images/with_mark.png'
      - '.github/workflows/**'
      - '.github/scripts/**.py'
  workflow_dispatch:

jobs:
  build_and_draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: '检出仓库代码 (Checkout repository)'
        uses: actions/checkout@v4

      - name: '设置 Python 3.9 环境 (Set up Python)'
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: '安装依赖库 (Install dependencies)'
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
          # 确保 numpy, opencv, easyocr 和 pillow 都被安装
          pip install numpy opencv-python-headless easyocr Pillow

      - name: '步骤 1: 从图片生成岩点坐标 (Generate Hold Coordinates)'
        run: |
          python .github/scripts/generate_coords.py

      - name: '步骤 2: 为每条路线绘制图片 (Draw Route Images)'
        run: |
          for route_file in routes/*.json; do
            if [ -f "$route_file" ]; then
              echo ">>> Processing route: $route_file"
              python .github/scripts/draw_route.py "$route_file"
            fi
          done

      - name: '步骤 3: 提交生成的文件 (Commit generated files)'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(routes): 自动生成路线图和坐标"
          file_pattern: "data/holds.json generated_routes/*.png"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      - name: '检查未识别的岩点'
        run: |
          python .github/scripts/check_missing_holds.py

      - name: '步骤 1.5: 标注所有岩点坐标到 debug_mark.png'
        run: |
          python .github/scripts/mark_all_holds.py
