name: Generate Route Images

# --- 触发工作流的条件 ---
on:
  push:
    branches:
      - main # 只在 main 分支生效
    paths:
      - 'routes/**.json'        # 当路线文件被添加或修改时
      - 'images/with_mark.png'  # 当带标记的图片更新时
      - '.github/workflows/**'  # 当工作流本身被修改时
      - 'scripts/**.py'         # 当处理脚本被修改时
  workflow_dispatch: # 允许手动触发

jobs:
  build_and_draw:
    runs-on: ubuntu-latest

    # --- 赋予工作流写回仓库的权限 ---
    permissions:
      contents: write

    steps:
      - name: 检出仓库代码 (Checkout repository)
        uses: actions/checkout@v4

      - name: 设置 Python 3.9 环境 (Set up Python)
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: 安装依赖库 (Install dependencies)
        run: |
          python -m pip install --upgrade pip
          # easyocr 依赖 PyTorch，这是一个比较大的库
          echo "Installing PyTorch..."
          pip install torch torchvision torchaudio
          echo "Installing easyocr and Pillow..."
          pip install easyocr Pillow
          echo "Installation complete."

      - name: 步骤 1: 从图片生成岩点坐标 (Generate Hold Coordinates)
        id: generate_coords
        run: |
          echo "Running OCR script to generate coordinates..."
          python scripts/generate_coords.py
          echo "Coordinates file 'data/holds.json' has been generated."

      - name: 步骤 2: 为每条路线绘制图片 (Draw Route Images)
        id: draw_routes
        run: |
          # 查找 routes 目录下的所有 .json 文件，并为每一个生成图片
          for route_file in routes/*.json; do
            if [ -f "$route_file" ]; then
              echo ">>> Processing route: $route_file"
              python scripts/draw_route.py "$route_file"
            fi
          done
          echo "All routes have been processed."

      - name: 步骤 3: 提交生成的文件 (Commit generated files)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(routes): 自动生成路线图和坐标"
          # 指定要提交的文件
          file_pattern: "data/holds.json generated_routes/*.png"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
