name: Generate Route Images

on:
  push:
    branches:
      - main
    paths:
      - 'routes/all_routes.json' 
      - 'images/with_mark.png'
      - '.github/workflows/**'
      - '.github/scripts/**.py'
  workflow_dispatch:

jobs:
  build_and_draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: '检出仓库代码 (Checkout repository)'
        uses: actions/checkout@v4

      - name: '设置 Python 3.9 环境 (Set up Python)'
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: '缓存 Pip 依赖 (Cache Pip dependencies)'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: '安装依赖库 (Install dependencies)'
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
          pip install numpy opencv-python-headless easyocr Pillow

      # --- **核心修改点: 新增下载字体的步骤** ---
      - name: '下载并准备字体文件 (Download and Prepare Font)'
        run: |
          # 1. 创建 fonts 文件夹
          mkdir -p fonts
          # 2. 使用 curl 下载字体文件，并重命名
          #    -L 选项用于处理重定向
          #    -o 指定输出路径和文件名
          curl -L "https://github.com/google/fonts/raw/main/ofl/oswald/Oswald%5Bwght%5D.ttf" -o "fonts/Oswald-Variable.ttf"
          echo "Font Oswald-Variable.ttf downloaded to fonts/ directory."

      - name: '步骤 1: 从图片生成岩点坐标 (Generate Hold Coordinates)'
        run: |
          python .github/scripts/generate_coords.py \
            --image_path "images/with_mark.png" \
            --output_path "data/holds.json"

      - name: '步骤 2: 标注所有岩点坐标用于调试 (Mark all holds for debugging)'
        run: |
          python .github/scripts/mark_all_holds.py

      - name: '步骤 3: 为所有路线绘制图片 (Draw All Route Images)'
        run: |
          echo ">>> Processing all routes from routes/all_routes.json"
          python .github/scripts/draw_route.py "routes/all_routes.json"

      - name: '步骤 4: 提交生成的文件 (Commit generated files)'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(routes): 自动生成所有路线图"
          # 只提交实际生成的核心文件
          file_pattern: "data/holds.json generated_routes/*.png"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      - name: '步骤 5: 压缩所有路线图为ZIP包 (Compress all route images into a ZIP)'
        if: always()
        run: |
          zip -r climbing_routes.zip generated_routes

      - name: '步骤 6: 上传路线图压缩包 (Upload Route Images Artifact)'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: climbing-routes-images
          path: climbing_routes.zip

      - name: '步骤 7: 检查未识别的岩点 (Check for missing holds)'
        if: always()
        run: |
          python .github/scripts/check_missing_holds.py
